// MijnApp-Frontend-React/src/components/always-safe.js
import React from "react";
import { Container, Button, Grid, Link } from "@material-ui/core";
import { makeStyles } from "@material-ui/core/styles";

function AlwaysSafe(props) {
  const handleLogin = () => {
    props.history.push("/login");
  };
  const useStyles = makeStyles((theme) => ({
    root: {
      paddingTop: 0,
    },
    menuButton: {
      marginRight: theme.spacing(2),
    },
    title: {
      flexGrow: 1,
    },
    container: {
      backgroundColor: "#f9f9f9",
      height: "90vh",
    },
    wrapIcon: {
      verticalAlign: "middle",
    },
    buttonOrange: {
      backgroundColor: theme.palette.warning.dark + "!important",
      height: 40,
      width: "95%",
      textTransform: "none",
      marginTop: "2px",
      color: "white",
      fontWeight: "bold",
      justifyContent: "center",
    },
    image: {
      marginLeft: "10px",
      marginTop: "3px",
      height: 20,
    },
    screenImage: {
      height: 350,
      width: 300,
      alignItems: "center",
    },
  }));

  const classes = useStyles();
  return (
    <Container maxWidth="sm" className={classes.container}>
      <Grid
        container
        flexGrow="1"
        direction="column"
        alignItems="center"
        justify="center"
      >
        <Grid>
          <span className="mui--pull-left">Welkomstour</span>
          <span className="mui--pull-right">
            <Link href="login" className="link">
              Overlaan
            </Link>
          </span>
        </Grid>
        <Grid container className={classes.wrapIcon}>
          <strong>Altijd veilig</strong>
          <br />
          <p>
            Alleen jij hebt toegang tot je eigen gegevens. Deze zijn vergrendeld
            via een pincode of biometrische scan.
          </p>
        </Grid>
        <Grid container justifyContent="center">
          <img src="/screen3.png" alt="img" className={classes.screenImage} />
        </Grid>
        <Grid container>
          <Button className={classes.buttonOrange} onClick={handleLogin}>
            Go door naar inloggen
            <img src="/Arrow-forward-w.png" alt="img" />
          </Button>
        </Grid>
      </Grid>
    </Container>
  );
}

export default AlwaysSafe;

// MijnApp-Frontend-Angular/src/app/welcome-tour/always-safe/always-safe.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-always-safe',
  templateUrl: './always-safe.component.html',
  styleUrls: ['./always-safe.component.scss']
})
export class AlwaysSafeComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<div class="page-wrapper">
  <div class="page_name">
    <div class="title">
      <div>Welkomstour</div>
      <div><a routerLink="../login" class="link">Overlaan</a></div>
    </div>
  </div>
  <ul class="statusbar">
    <li class="active"></li>
    <li class="active"></li>
    <li class="active"></li>
  </ul>
  <div class="contentpart d-flex">
    <div>
      <h3>Altijd veilig</h3>
      <p>
        Alleen jij hebt toegang tot je eigen gegevens. Deze zijn vergrendeld via
        een pincode of biometrische scan.
      </p>
    </div>
    <div class="text-center screenimg">
      <img src="/assets/img/screen3.png" />
    </div>
  </div>

  <div class="btnrow2">
    <a class="orangebtn cursor-pointer" routerLink="../login">
      <div class="d-inline-flex">
        Ga door naar inloggen
        <div class="ml-2"><img src="/assets/img/Arrow-forward-w.png" /></div>
      </div>
    </a>
  </div>
</div>
